### PR TITLE
Fix artists importing

### PR DESCRIPTION
**Pull request by navel**
image
`ERROR - An unexpected error occurred: 'Artist' object has no attribute 'artists'`

### CODE REVIEW

**Comment by MarshalX** [comment]
which solution is more correct? we have another one https://github.com/MarshalX/yandex2spotify/pull/50

**Comment by artembaechka** [comment]
> which solution is more correct? we have another one #50

This more readeble code, i think this solution better

**Comment by MarshalX** [comment]
> > which solution is more correct? we have another one #50
> 
> This more readeble code, i think this solution better

but i don't get it. why do we put class on the list

**Comment by artembaechka** [comment]
> > > which solution is more correct? we have another one #50
> > 
> > This more readeble code, i think this solution better
> 
> but i don't get it. why do we put class on the list 

Oh really, i dont seen that. Now idk what code correct

**Pull request closed without merging**
