### PR TITLE
file format check

### LINKED ISSUE #11: Exception thrown when importing playlist
```2020-07-20 16:43:25,150 - INFO - Importing playlist ANIIML - SLAY! (2018)...
2020-07-20 16:43:28,983 - WARNING - Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
2020-07-20 16:43:28,987 - WARNING - Type: <class 'yandex_music.track.meta_data.MetaData'>; kwargs: {'version': 'Visit http://aniimlmusic.bandcamp.com'}
2020-07-20 16:43:28,992 - INFO - Importing track: ANIIML - SLAY!...
2020-07-20 16:43:29,191 - INFO - OK
2020-07-20 16:43:29,191 - INFO - Saving 1 tracks in playlist ANIIML - SLAY! (2018)...
2020-07-20 16:43:29,407 - INFO - OK
2020-07-20 16:43:29,641 - INFO - Importing playlist LEViT∆TE - Fatalism EP (2019)...
Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "importer.py", line 233, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore).import_all()
  File "importer.py", line 190, in import_all
    item()
  File "importer.py", line 144, in import_playlists
    self.spotify_client.playlist_upload_cover_image(spotify_playlist_id, encode_file_base64(filename_jpg))
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 553, in playlist_upload_cover_image
    content_type="image/jpeg",
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 225, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 172, in _internal_call
    timeout=self.requests_timeout, **args
  File "/home/tu/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))```

### PR DESCRIPTION
**Pull request by MarshalX**
close #11

### CODE REVIEW

**Comment by karrakoliko** [comment]
@MarshalX as you asked, i tested this branch.
got another exception.

```2020-07-20 17:39:15,895 - ERROR - Couldn't refresh token. Response Status Code: 400 Reason: Bad Request
Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/oauth2.py", line 512, in refresh_access_token
    response.raise_for_status()
  File "/home/tu/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "importer.py", line 235, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore).import_all()
  File "importer.py", line 192, in import_all
    item()
  File "importer.py", line 131, in import_likes
    self._add_items_to_spotify(tracks, self.not_imported['Likes'], save_tracks_callback, Type.TRACK)
  File "importer.py", line 108, in _add_items_to_spotify
    found_items = self.spotify_client.search(item_name, type=type_.value)[f'{type_.value}s']['items']
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 464, in search
    "search", q=q, limit=limit, offset=offset, type=type, market=market
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 210, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 154, in _internal_call
    headers = self._auth_headers()
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 145, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/oauth2.py", line 448, in get_access_token
    token_info = self.get_cached_token()
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/oauth2.py", line 294, in get_cached_token
    token_info["refresh_token"]
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/oauth2.py", line 524, in refresh_access_token
    headers)
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - Couldn't refresh token: code:400 reason:Bad Request
```

i'm not sure whether it related or not

**Comment by MarshalX** [comment]
@vtuu thanks! Delete the file from the folder that starts with .cache and run again

**Comment by karrakoliko** [comment]
Oh, i know why this happened: I revoked token access in Spotify.
Sorry for inconvenience, will fix now

**Comment by karrakoliko** [comment]
```
2020-07-20 17:48:22,254 - INFO - Importing playlist LEViT∆TE - Fatalism EP (2019)...
Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "importer.py", line 235, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore).import_all()
  File "importer.py", line 192, in import_all
    item()
  File "importer.py", line 146, in import_playlists
    self.spotify_client.playlist_upload_cover_image(spotify_playlist_id, encode_file_base64(filename_jpg))
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 553, in playlist_upload_cover_image
    content_type="image/jpeg",
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 225, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 172, in _internal_call
    timeout=self.requests_timeout, **args
  File "/home/tu/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by karrakoliko** [comment]
IMO extension/format validation should not be inisde of png2jpg function, but one level higher: in the place of its calling.
png2jpg should not be called if given file is not png

**Comment by MarshalX** [comment]
@vtuu let's try again)

**Comment by karrakoliko** [comment]
```
2020-07-20 18:03:21,868 - INFO - Importing playlist LEViT∆TE - Fatalism EP (2019)...
2020-07-20 18:03:26,291 - WARNING - Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
2020-07-20 18:03:26,295 - WARNING - Type: <class 'yandex_music.track.meta_data.MetaData'>; kwargs: {'version': 'Visit http://levitatemusic.bandcamp.com'}
2020-07-20 18:03:26,297 - WARNING - Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
2020-07-20 18:03:26,300 - WARNING - Type: <class 'yandex_music.track.meta_data.MetaData'>; kwargs: {'version': 'Visit http://levitatemusic.bandcamp.com'}
2020-07-20 18:03:26,301 - WARNING - Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
2020-07-20 18:03:26,308 - WARNING - Type: <class 'yandex_music.track.meta_data.MetaData'>; kwargs: {'version': 'Visit http://levitatemusic.bandcamp.com'}
2020-07-20 18:03:26,309 - WARNING - Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
2020-07-20 18:03:26,312 - WARNING - Type: <class 'yandex_music.track.meta_data.MetaData'>; kwargs: {'version': 'Visit http://levitatemusic.bandcamp.com'}
2020-07-20 18:03:26,314 - INFO - Importing track: LEViT∆TE - I'll Pray For You...
2020-07-20 18:03:26,517 - INFO - OK
2020-07-20 18:03:26,518 - INFO - Importing track: LEViT∆TE - Wasting Your Breath...
2020-07-20 18:03:26,741 - INFO - OK
2020-07-20 18:03:26,743 - INFO - Importing track: LEViT∆TE - Pitchblaque...
2020-07-20 18:03:26,941 - INFO - OK
2020-07-20 18:03:26,943 - INFO - Importing track: LEViT∆TE - In This City...
2020-07-20 18:03:27,141 - INFO - OK
2020-07-20 18:03:27,141 - INFO - Saving 4 tracks in playlist LEViT∆TE - Fatalism EP (2019)...
2020-07-20 18:03:27,357 - INFO - OK
2020-07-20 18:03:27,588 - INFO - Importing playlist ANIIML - We.Animals (2015)...
Traceback (most recent call last):
  File "importer.py", line 235, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore).import_all()
  File "importer.py", line 192, in import_all
    item()
  File "importer.py", line 160, in import_playlists
    self._add_items_to_spotify(tracks, self.not_imported[playlist.title], save_tracks_callback, Type.TRACK)
  File "importer.py", line 100, in _add_items_to_spotify
    if item.available:
AttributeError: 'NoneType' object has no attribute 'available'
```

Stopped on another playlist with custom tracks and cover: https://clck.ru/PmRz5

**Comment by MarshalX** [comment]
> IMO extension/format validation should not be inisde of png2jpg function, but one level higher: in the place of its calling.
> png2jpg should not be called if given file is not png

I completely agree. Now the main thing is to get it working

**Comment by MarshalX** [comment]
@vtuu idk how I can reproduce it... Of course I can add "if" and it will help, but it misses some tracks

**Comment by karrakoliko** [comment]
@MarshalX you are developer, the only thing i can help here is to provide stack trace: i can't help with python.
Here is another one:
```
2020-07-20 18:14:07,578 - INFO - Importing playlist ANIIML - SLAY! (2018)...
Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 326, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tu/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/tu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "importer.py", line 235, in <module>
    Importer(spotify_client_, yandex_client_, arguments.ignore).import_all()
  File "importer.py", line 192, in import_all
    item()
  File "importer.py", line 146, in import_playlists
    self.spotify_client.playlist_upload_cover_image(spotify_playlist_id, encode_file_base64(filename_jpg))
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 553, in playlist_upload_cover_image
    content_type="image/jpeg",
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 225, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/spotipy/client.py", line 172, in _internal_call
    timeout=self.requests_timeout, **args
  File "/home/tu/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/tu/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)
```

**Pull request merged**
